CREATE TABLE [EquipData] (
	[OrgId] [int] NOT NULL ,
	[Id] [int] IDENTITY (1, 1) NOT NULL ,
	[intCreatedBy] [int] NULL ,
	[dtCreated] [datetime] NOT NULL CONSTRAINT [DF_EquipData_dtCreated] DEFAULT (getutcdate()),,
	[intUpdatedBy] [int] NULL ,
	[dtUpdated] [datetime] NOT NULL CONSTRAINT [DF_EquipData_dtUpdated] DEFAULT (getutcdate()),
	[vchOrdering] [varchar] (512) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ftItemOrder] [float] NULL ,
	[intSize] [int] NOT NULL CONSTRAINT [DF_EquipData_intSize] DEFAULT (0),
	[nvarchar1] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar2] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar3] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar4] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar5] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar6] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar7] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar8] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar9] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar10] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar11] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar12] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar13] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar14] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar15] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar16] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar17] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar18] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar19] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar20] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar21] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar22] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar23] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar24] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar25] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar26] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar27] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar28] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar29] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar30] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar31] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar32] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar33] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar34] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar35] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar36] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar37] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar38] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar39] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar40] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar41] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar42] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar43] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar44] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar45] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar46] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar47] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar48] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar49] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar50] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar51] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar52] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar53] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar54] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar55] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar56] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar57] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar58] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar59] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar60] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar61] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar62] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar63] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[nvarchar64] [nvarchar] (255) COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[int1] [int] NULL ,
	[int2] [int] NULL ,
	[int3] [int] NULL ,
	[int4] [int] NULL ,
	[int5] [int] NULL ,
	[int6] [int] NULL ,
	[int7] [int] NULL ,
	[int8] [int] NULL ,
	[int9] [int] NULL ,
	[int10] [int] NULL ,
	[int11] [int] NULL ,
	[int12] [int] NULL ,
	[int13] [int] NULL ,
	[int14] [int] NULL ,
	[int15] [int] NULL ,
	[int16] [int] NULL ,
	[float1] [float] NULL ,
	[float2] [float] NULL ,
	[float3] [float] NULL ,
	[float4] [float] NULL ,
	[float5] [float] NULL ,
	[float6] [float] NULL ,
	[float7] [float] NULL ,
	[float8] [float] NULL ,
	[float9] [float] NULL ,
	[float10] [float] NULL ,
	[float11] [float] NULL ,
	[float12] [float] NULL ,
	[float13] [float] NULL ,
	[float14] [float] NULL ,
	[float15] [float] NULL ,
	[float16] [float] NULL ,
	[float17] [float] NULL ,
	[float18] [float] NULL ,
	[float19] [float] NULL ,
	[float20] [float] NULL ,
	[float21] [float] NULL ,
	[float22] [float] NULL ,
	[float23] [float] NULL ,
	[float24] [float] NULL ,
	[float25] [float] NULL ,
	[float26] [float] NULL ,
	[float27] [float] NULL ,
	[float28] [float] NULL ,
	[float29] [float] NULL ,
	[float30] [float] NULL ,
	[float31] [float] NULL ,
	[float32] [float] NULL ,
	[datetime1] [datetime] NULL ,
	[datetime2] [datetime] NULL ,
	[datetime3] [datetime] NULL ,
	[datetime4] [datetime] NULL ,
	[datetime5] [datetime] NULL ,
	[datetime6] [datetime] NULL ,
	[datetime7] [datetime] NULL ,
	[datetime8] [datetime] NULL ,
	[datetime9] [datetime] NULL ,
	[datetime10] [datetime] NULL ,
	[datetime11] [datetime] NULL ,
	[datetime12] [datetime] NULL ,
	[datetime13] [datetime] NULL ,
	[datetime14] [datetime] NULL ,
	[datetime15] [datetime] NULL ,
	[datetime16] [datetime] NULL ,
	[bit1] [bit] NULL ,
	[bit2] [bit] NULL ,
	[bit3] [bit] NULL ,
	[bit4] [bit] NULL ,
	[bit5] [bit] NULL ,
	[bit6] [bit] NULL ,
	[bit7] [bit] NULL ,
	[bit8] [bit] NULL ,
	[bit9] [bit] NULL ,
	[bit10] [bit] NULL ,
	[bit11] [bit] NULL ,
	[bit12] [bit] NULL ,
	[bit13] [bit] NULL ,
	[bit14] [bit] NULL ,
	[bit15] [bit] NULL ,
	[bit16] [bit] NULL ,
	[ntext1] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext2] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext3] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext4] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext5] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext6] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext7] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext8] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext9] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext10] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext11] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext12] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext13] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext14] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext15] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext16] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext17] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext18] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext19] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext20] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext21] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext22] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext23] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext24] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext25] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext26] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext27] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext28] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext29] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext30] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext31] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[ntext32] [ntext] COLLATE Latin1_General_CI_AS_KS_WS NULL ,
	[sql_variant1] [sql_variant] NULL ,
	[sql_variant2] [sql_variant] NULL ,
	[sql_variant3] [sql_variant] NULL ,
	[sql_variant4] [sql_variant] NULL ,
	[sql_variant5] [sql_variant] NULL ,
	[sql_variant6] [sql_variant] NULL ,
	[sql_variant7] [sql_variant] NULL ,
	[sql_variant8] [sql_variant] NULL ,
	CONSTRAINT [EquipData_PK] PRIMARY KEY  CLUSTERED 
	(
		[OrgId],
		[Id]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


